theme: minima
minima:
  skin: auto
  nav_pages:
    - about.md
    - portfolio.md
  social_links:
    - title: Страничка автора ВК
      icon: vk
      url: "https://vk.com/clonikl/"
    - title: Автор в тг
      icon: telegram
      url: "https://t.me/clonikl"
